<!-- wp:ablocks/academy-certificate {"block_id":"d3312d49-dc7b-4c78-9e0a-eb9ea414322f","backgroundImage":"<?php echo esc_url( ACADEMY_ASSETS_URI . 'images/certificate/certificate-1.png' ); ?>","imageOptions":[{"label":"cert_1","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-1.png" ); ?>"},{"label":"cert_2","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-2.png" ); ?>"},{"label":"cert_3","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-3.png" ); ?>"},{"label":"cert_4","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-4.png" ); ?>"},{"label":"cert_5","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-5.png" ); ?>"},{"label":"cert_6","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-6.png" ); ?>"},{"label":"cert_7","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/certificate-7.png" ); ?>"},{"label":"custom_image","value":"<?php echo esc_url( ACADEMY_ASSETS_URI . "images/certificate/custom_upload.png" ); ?>"}],"containerWidth":100} -->
	<div class="ablocks-block ablocks-block-d3312d49-dc7b-4c78-9e0a-eb9ea414322f ablocks-block--academy-certificate"><div class="ablocks-block-container"><div class="ablocks-block--certificate__background-image"><div class="ablocks-block--certificate__background-image-inner-block"><!-- wp:image {"id":64,"sizeSlug":"full","linkDestination":"none","align":"center"} -->
<figure class="wp-block-image aligncenter size-full">
	<?php // phpcs:ignore PluginCheck.CodeAnalysis.ImageFunctions.NonEnqueuedImage ?>
	<img src="<?php echo esc_url( ACADEMY_ASSETS_URI . 'images/certificate/academy-logo.png' ); ?>" alt="" class="wp-image-64"/>
</figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":"42px"} -->
<div style="height:42px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:ablocks/academy-certificate-text {"block_id":"1f7960a7-dafc-4f42-9a46-6e38c0e03e32","alignment":{"value":"center"},"typography":{"fontFamily":"Grenze Gotisch","fontSize":52,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px","lineHeight":50},"_margin":{"isLinked":false,"isLinkedTablet":true,"isLinkedMobile":true,"commonTablet":"","commonMobile":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitTablet":"","unitMobile":""},"_padding":{"isLinked":false,"isLinkedTablet":true,"isLinkedMobile":true,"commonTablet":"","commonMobile":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitTablet":"","unitMobile":""}} -->
<div class="ablocks-block ablocks-block-1f7960a7-dafc-4f42-9a46-6e38c0e03e32 ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><h2 class="ablocks-block--certificate__heading-text">CERTIFICATE OF ACHIEVEMENT</h2></div></div>
<!-- /wp:ablocks/academy-certificate-text -->

<!-- wp:spacer {"height":"58px"} -->
<div style="height:58px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:ablocks/academy-certificate-text {"block_id":"c7299171-94da-43f6-bc48-9c2b70bd23f6","headingTag":"span","alignment":{"value":"center"},"typography":{"fontFamily":"Poppins","fontSize":17,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px"}} -->
<div class="ablocks-block ablocks-block-c7299171-94da-43f6-bc48-9c2b70bd23f6 ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><span class="ablocks-block--certificate__heading-text">Presented to</span></div></div>
<!-- /wp:ablocks/academy-certificate-text -->

<!-- wp:ablocks/academy-certificate-text {"block_id":"a70e97ad-c2f9-4efa-bfe0-a945b3596947","alignment":{"value":"center"},"typography":{"fontFamily":"Great Vibes","fontSize":90,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px"},"_margin":{"isLinked":false,"top":"0"},"_padding":{"isLinked":false,"isLinkedTablet":true,"isLinkedMobile":true,"commonTablet":"","commonMobile":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitTablet":"","unitMobile":""}} -->
<div class="ablocks-block ablocks-block-a70e97ad-c2f9-4efa-bfe0-a945b3596947 ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><h2 class="ablocks-block--certificate__heading-text"> {{learner}}</h2></div></div>
<!-- /wp:ablocks/academy-certificate-text -->

<!-- wp:spacer {"height":"57px"} -->
<div style="height:57px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:ablocks/academy-certificate-text {"block_id":"a7bc070b-0a41-4817-90d4-7b3515a584f8","headingTag":"span","alignment":{"value":"center"},"typography":{"fontFamily":"Poppins","fontSize":16,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px"}} -->
<div class="ablocks-block ablocks-block-a7bc070b-0a41-4817-90d4-7b3515a584f8 ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><span class="ablocks-block--certificate__heading-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreevtum zzril delenit augue</span></div></div>
<!-- /wp:ablocks/academy-certificate-text -->

<!-- wp:spacer {"height":"99px"} -->
<div style="height:99px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:ablocks/academy-container {"block_id":"23375f57-685c-45fd-a548-9ed6f27f6146","containerWidth":{"value":450},"floatAlignment":{"value":"left","valueTablet":"","valueMobile":""},"floatMargin":{"isLinked":true,"isLinkedTablet":true,"isLinkedMobile":true,"common":"","top":"","right":"","bottom":"","left":"50","unit":"px","commonTablet":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","unitTablet":"","commonMobile":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitMobile":""},"variationSelected":true} -->
<div class="ablocks-block ablocks-block-23375f57-685c-45fd-a548-9ed6f27f6146 ablocks-block--academy-container"><div class="ablocks-block-container"><div class="academy-inner-container"><!-- wp:ablocks/academy-container {"block_id":"82bea440-0092-4cad-bfa2-7f6b8435fc2d","containerWidth":{"value":150},"floatAlignment":{"value":"","valueTablet":"","valueMobile":""},"floatMargin":{"isLinked":true,"isLinkedTablet":true,"isLinkedMobile":true,"common":"","top":"","right":"","bottom":"","left":"","unit":"px","commonTablet":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","unitTablet":"","commonMobile":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitMobile":""},"variationSelected":true} -->
<div class="ablocks-block ablocks-block-82bea440-0092-4cad-bfa2-7f6b8435fc2d ablocks-block--academy-container"><div class="ablocks-block-container"><div class="academy-inner-container"><!-- wp:ablocks/academy-container {"block_id":"f961f8b6-e4ee-4a12-b4c4-74d49fc38be7","containerWidth":{"value":99,"valueUnit":"%"},"floatAlignment":{"value":"","valueTablet":"","valueMobile":""},"floatMargin":{"isLinked":true,"isLinkedTablet":true,"isLinkedMobile":true,"common":"","top":"","right":"","bottom":"","left":"","unit":"px","commonTablet":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","unitTablet":"","commonMobile":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitMobile":""},"variationSelected":true} -->
<div class="ablocks-block ablocks-block-f961f8b6-e4ee-4a12-b4c4-74d49fc38be7 ablocks-block--academy-container"><div class="ablocks-block-container"><div class="academy-inner-container"><!-- wp:ablocks/academy-certificate-text {"block_id":"4c160ab0-44f5-42a8-ba92-4482cfa7d0a0","alignment":{"value":"center","valueTablet":"","valueMobile":""},"typography":{"fontSize":16,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px","fontFamily":"Poppins","letterSpacing":3,"weight":"400"},"_padding":{"isLinked":false,"top":"10","unit":"px"},"_border":{"borderStyle":"solid","isLinkedWidth":false,"topWidth":"1","unitWidth":"px","unitWidthH":"px","unitRadius":"px","unitRadiusH":"px"}} -->
<div class="ablocks-block ablocks-block-4c160ab0-44f5-42a8-ba92-4482cfa7d0a0 ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><h2 class="ablocks-block--certificate__heading-text">Date</h2></div></div>
<!-- /wp:ablocks/academy-certificate-text --></div></div></div>
<!-- /wp:ablocks/academy-container --></div></div></div>
<!-- /wp:ablocks/academy-container -->

<!-- wp:ablocks/academy-container {"block_id":"3aded6f6-119a-47b8-8dee-489b9ce4048a","containerWidth":{"value":150},"floatAlignment":{"value":"right"},"floatMargin":{"isLinked":true,"isLinkedTablet":true,"isLinkedMobile":true,"common":"","top":"","right":"","bottom":"","left":"","unit":"%","commonTablet":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","unitTablet":"","commonMobile":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitMobile":""},"variationSelected":true} -->
<div class="ablocks-block ablocks-block-3aded6f6-119a-47b8-8dee-489b9ce4048a ablocks-block--academy-container"><div class="ablocks-block-container"><div class="academy-inner-container"><!-- wp:ablocks/academy-container {"block_id":"1dd93e65-2eba-4213-b688-ba42b029c5bd","containerWidth":{"value":99,"valueUnit":"%"},"floatAlignment":{"value":"none"},"floatMargin":{"isLinked":true,"isLinkedTablet":true,"isLinkedMobile":true,"common":"","top":"","right":"","bottom":"","left":"","unit":"%","commonTablet":"","topTablet":"","rightTablet":"","bottomTablet":"","leftTablet":"","unitTablet":"","commonMobile":"","topMobile":"","rightMobile":"","bottomMobile":"","leftMobile":"","unitMobile":""},"variationSelected":true} -->
<div class="ablocks-block ablocks-block-1dd93e65-2eba-4213-b688-ba42b029c5bd ablocks-block--academy-container"><div class="ablocks-block-container"><div class="academy-inner-container"><!-- wp:ablocks/academy-certificate-text {"block_id":"fd27c0b6-b513-4a29-9d14-782c256bf15d","alignment":{"value":"center","valueTablet":"","valueMobile":""},"typography":{"fontSize":16,"fontSizeTablet":"","fontSizeMobile":"","fontSizeUnitTablet":"px","fontSizeUnitMobile":"px","lineHeightTablet":"","lineHeightMobile":"","lineHeightUnitTablet":"px","lineHeightUnitMobile":"px","letterSpacingTablet":"","letterSpacingMobile":"","letterSpacingUnitTablet":"px","letterSpacingUnitMobile":"px","wordSpacingTablet":"","wordSpacingMobile":"","wordSpacingUnitTablet":"px","wordSpacingUnitMobile":"px","fontFamily":"Poppins","letterSpacing":2,"weight":"400"},"_padding":{"isLinked":false,"top":"10","unit":"px"},"_border":{"borderStyle":"solid","isLinkedWidth":false,"topWidth":"1","unitWidth":"px","unitWidthH":"px","unitRadius":"px","unitRadiusH":"px"}} -->
<div class="ablocks-block ablocks-block-fd27c0b6-b513-4a29-9d14-782c256bf15d ablocks-block--academy-certificate-text"><div class="ablocks-block-container"><h2 class="ablocks-block--certificate__heading-text">Signature</h2></div></div>
<!-- /wp:ablocks/academy-certificate-text --></div></div></div>
<!-- /wp:ablocks/academy-container --></div></div></div>
<!-- /wp:ablocks/academy-container --></div></div></div>
<!-- /wp:ablocks/academy-container --></div></div></div></div>
<!-- /wp:ablocks/academy-certificate -->
