<?php
/**
 * Seeds simple products (physical + digital) each with a one-time price.
 *
 * @package StoreEngine\Addons\Seeder\Providers
 */

namespace StoreEngine\Addons\Seeder\Providers;

use StoreEngine\Addons\Seeder\Classes\AbstractSeederProvider;
use StoreEngine\Addons\Seeder\Classes\SeederContext;
use StoreEngine\Addons\Seeder\Classes\SeederData;
use StoreEngine\Classes\Price;
use StoreEngine\Classes\Product\SimpleProduct;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ProductProvider extends AbstractSeederProvider {

	public function get_key(): string {
		return 'products';
	}

	public function get_label(): string {
		return 'Products';
	}

	public function get_default_count(): int {
		return 12;
	}

	public function seed( SeederContext $context, int $count ): void {
		for ( $i = 0; $i < $count; $i++ ) {
			$name          = SeederData::product_name();
			$shipping_type = SeederData::pick( [ 'physical', 'physical', 'digital' ] );

			$product = new SimpleProduct();
			$product->set_name( $name );
			$product->set_type( 'simple' );
			$product->set_shipping_type( $shipping_type );
			$product->set_content( 'Sample product generated by the StoreEngine seeder for testing.' );
			$product->set_status( 'publish' );
			$product->save();

			$product_id = $product->get_id();
			if ( ! $product_id ) {
				continue;
			}

			update_post_meta( $product_id, SeederData::MARKER_META, 1 );
			$context->record( 'product', $product_id );

			// A product is only sellable once it has a price row.
			$price = new Price();
			$price->set_product_id( $product_id );
			$price->set_price_name( 'Standard' );
			$price->set_price_type( 'onetime' );
			$price->set_price( SeederData::price() );
			$price->save();

			$price_id = $price->get_id();
			if ( $price_id ) {
				$context->record( 'price', $price_id );
			}
		}
	}
}
