<?php
/**
 * Seeds subscriptions for the Subscription addon.
 *
 * Self-contained: creates its own subscription products + recurring prices
 * (the core product provider only makes one-time prices), then a spread of
 * subscriptions for seeded customers. Only registered while the subscription
 * addon is active (see the seeder addon's register_providers()).
 *
 * @package StoreEngine\Addons\Seeder\Providers
 */

namespace StoreEngine\Addons\Seeder\Providers;

use StoreEngine\Addons\Seeder\Classes\AbstractSeederProvider;
use StoreEngine\Addons\Seeder\Classes\SeederContext;
use StoreEngine\Addons\Seeder\Classes\SeederData;
use StoreEngine\Addons\Subscription\Classes\Subscription;
use StoreEngine\Classes\Price;
use StoreEngine\Classes\Product\SimpleProduct;
use StoreEngine\Utils\Constants;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class SubscriptionProvider extends AbstractSeederProvider {

	/**
	 * Recurring plans to spin up products for. [ label, price, duration, type ].
	 *
	 * @var array<int, array{0:string,1:float,2:int,3:string}>
	 */
	private array $plans = [
		[ 'Monthly Plan', 9.99, 1, 'month' ],
		[ 'Annual Plan', 99.00, 1, 'year' ],
	];

	/**
	 * Weighted status pool — mostly active.
	 *
	 * @var string[]
	 */
	private array $status_pool = [
		Constants::SUBSCRIPTION_STATUS_ACTIVE,
		Constants::SUBSCRIPTION_STATUS_ACTIVE,
		Constants::SUBSCRIPTION_STATUS_ACTIVE,
		Constants::SUBSCRIPTION_STATUS_ON_HOLD,
		Constants::SUBSCRIPTION_STATUS_PENDING,
		Constants::SUBSCRIPTION_STATUS_CANCELLED,
	];

	public function get_key(): string {
		return 'subscriptions';
	}

	public function get_label(): string {
		return 'Subscriptions';
	}

	public function get_default_count(): int {
		return 8;
	}

	public function get_dependencies(): array {
		return [ 'customers' ];
	}

	public function seed( SeederContext $context, int $count ): void {
		$plan_prices = $this->seed_plan_products( $context );
		if ( empty( $plan_prices ) ) {
			return;
		}

		$customer_ids = $context->ids( 'customers', 'customer' );

		for ( $i = 0; $i < $count; $i++ ) {
			$customer_id = $customer_ids ? (int) SeederData::pick( $customer_ids ) : 0;
			$plan        = SeederData::pick( $plan_prices );
			$status      = SeederData::pick( $this->status_pool );
			$start_ts    = SeederData::past_timestamp( 200 );

			$subscription = new Subscription();
			$subscription->set_currency( 'USD' );
			$subscription->set_customer_id( $customer_id );
			$subscription->set_payment_method( 'seed_manual' );
			$subscription->set_payment_method_title( 'Seeded (manual)' );
			$subscription->set_requires_manual_renewal( true );
			$subscription->set_payment_duration( $plan['duration'] );
			$subscription->set_payment_duration_type( $plan['duration_type'] );
			$subscription->set_start_date( $start_ts );
			$subscription->set_next_payment_date( $this->next_payment_ts( $start_ts, $plan ) );
			$this->apply_billing( $subscription, $customer_id );

			$subscription->add_product( $plan['price_id'], 1 );
			$subscription->calculate_totals();
			$subscription->set_status( $status );

			$subscription_id = $subscription->save();
			if ( ! $subscription_id || is_wp_error( $subscription_id ) ) {
				continue;
			}

			$context->record( 'subscription', (int) $subscription_id );
		}
	}

	/**
	 * Create one digital product + recurring price per plan.
	 *
	 * @return array<int, array{price_id:int,duration:int,duration_type:string}>
	 */
	private function seed_plan_products( SeederContext $context ): array {
		$plan_prices = [];

		foreach ( $this->plans as [ $label, $amount, $duration, $duration_type ] ) {
			$product = new SimpleProduct();
			$product->set_name( 'Membership — ' . $label );
			$product->set_type( 'simple' );
			$product->set_shipping_type( 'digital' );
			$product->set_content( 'Sample subscription product generated by the StoreEngine seeder.' );
			$product->set_status( 'publish' );
			$product->save();

			$product_id = $product->get_id();
			if ( ! $product_id ) {
				continue;
			}

			update_post_meta( $product_id, SeederData::MARKER_META, 1 );
			$context->record( 'product', $product_id );

			$price = new Price();
			$price->set_product_id( $product_id );
			$price->set_price_name( $label );
			$price->set_price_type( 'subscription' );
			$price->set_price( $amount );
			$price->set_payment_duration( $duration );
			$price->set_payment_duration_type( $duration_type );
			$price->set_trial( false );
			$price->set_trial_days( 0 );
			$price->save();

			$price_id = $price->get_id();
			if ( ! $price_id ) {
				continue;
			}

			$context->record( 'price', $price_id );

			$plan_prices[] = [
				'price_id'      => $price_id,
				'duration'      => $duration,
				'duration_type' => $duration_type,
			];
		}

		return $plan_prices;
	}

	/**
	 * @param array{duration:int,duration_type:string} $plan
	 */
	private function next_payment_ts( int $start_ts, array $plan ): int {
		$next = strtotime( sprintf( '+%d %s', $plan['duration'], $plan['duration_type'] ), $start_ts );

		// If the computed date is already past, roll forward from now.
		return $next > time() ? $next : strtotime( sprintf( '+%d %s', $plan['duration'], $plan['duration_type'] ) );
	}

	private function apply_billing( Subscription $subscription, int $customer_id ): void {
		$first = SeederData::first_name();
		$last  = SeederData::last_name();
		$email = SeederData::email( $first, $last );

		if ( $customer_id ) {
			$user = get_userdata( $customer_id );
			if ( $user ) {
				$first = $user->first_name ?: $first;
				$last  = $user->last_name ?: $last;
				$email = $user->user_email ?: $email;
			}
		}

		$subscription->set_billing_first_name( $first );
		$subscription->set_billing_last_name( $last );
		$subscription->set_billing_email( $email );
		$subscription->set_order_email( $email );
	}
}
